# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 150, 906, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(50, 0, 50, 0)
        self.gridLayout_2.setHorizontalSpacing(80)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lightsB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lightsB.setObjectName("lightsB")
        self.gridLayout_2.addWidget(self.lightsB, 0, 2, 1, 1)
        self.camL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.camL.setObjectName("camL")
        self.gridLayout_2.addWidget(self.camL, 1, 3, 1, 1)
        self.camB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.camB.setObjectName("camB")
        self.gridLayout_2.addWidget(self.camB, 0, 3, 1, 1)
        self.dataComL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dataComL.setObjectName("dataComL")
        self.gridLayout_2.addWidget(self.dataComL, 1, 1, 1, 1)
        self.lightsL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lightsL.setObjectName("lightsL")
        self.gridLayout_2.addWidget(self.lightsL, 1, 2, 1, 1)
        self.powerB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.powerB.setObjectName("powerB")
        self.gridLayout_2.addWidget(self.powerB, 0, 4, 1, 1)
        self.dataComB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dataComB.setObjectName("dataComB")
        self.gridLayout_2.addWidget(self.dataComB, 0, 1, 1, 1)
        self.powerL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.powerL.setObjectName("powerL")
        self.gridLayout_2.addWidget(self.powerL, 1, 4, 1, 1)
        self.camP = QtWidgets.QLabel(self.centralwidget)
        self.camP.setGeometry(QtCore.QRect(540, 30, 131, 101))
        self.camP.setText("")
        self.camP.setPixmap(QtGui.QPixmap("images/cameraOff.png"))
        self.camP.setScaledContents(True)
        self.camP.setObjectName("camP")
        self.powerP = QtWidgets.QLabel(self.centralwidget)
        self.powerP.setGeometry(QtCore.QRect(760, 30, 131, 101))
        self.powerP.setText("")
        self.powerP.setPixmap(QtGui.QPixmap("images/powerSaveOff.png"))
        self.powerP.setScaledContents(True)
        self.powerP.setObjectName("powerP")
        self.lightsP = QtWidgets.QLabel(self.centralwidget)
        self.lightsP.setGeometry(QtCore.QRect(320, 30, 131, 101))
        self.lightsP.setText("")
        self.lightsP.setPixmap(QtGui.QPixmap("images/lightsOff.png"))
        self.lightsP.setScaledContents(True)
        self.lightsP.setObjectName("lightsP")
        self.dataComP = QtWidgets.QLabel(self.centralwidget)
        self.dataComP.setGeometry(QtCore.QRect(100, 30, 131, 101))
        self.dataComP.setText("")
        self.dataComP.setPixmap(QtGui.QPixmap("images/dataComOff.png"))
        self.dataComP.setScaledContents(True)
        self.dataComP.setObjectName("dataComP")
        self.logButton = QtWidgets.QPushButton(self.centralwidget)
        self.logButton.setGeometry(QtCore.QRect(860, 290, 131, 51))
        self.logButton.setObjectName("logButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lightsB.setText(_translate("MainWindow", "\n"
"Işıkları\n"
"Aç/Kapat\n"
""))
        self.camL.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.camB.setText(_translate("MainWindow", "\n"
"Kamerayı\n"
"Aç/Kapat\n"
""))
        self.dataComL.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lightsL.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.powerB.setText(_translate("MainWindow", "\n"
"Güç Tasarruf Modunu\n"
"Aç/Kapat\n"
""))
        self.dataComB.setText(_translate("MainWindow", "\n"
"Veri İletişimini\n"
"Başlat/Durdur\n"
""))
        self.powerL.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.logButton.setText(_translate("MainWindow", "Log Kayıt\n"
"Dosyasını Aç"))
